apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-frontend-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tts-frontend
  template:
    metadata:
      labels:
        app: tts-frontend
    spec:
      containers:
      - name: tts-frontend
        image: tts-frontend:2.0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /tts/upload
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /tts/upload
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20